### ISSUE TITLE
get_all generates dates incorrectly

### ISSUE THREAD

**Issue by Air2Air2Git** [kaiyoux/kwess#1]
get_all function is generating start datetime of the next range the same as the end datetime of the previous range. This results in duplicate records pulled from Questrade from those overlapping dates.

**Comment by kaiyoux** [comment]
> get_all function is generating start datetime of the next range the same as the end datetime of the previous range. This results in duplicate records pulled from Questrade from those overlapping dates.

Could you provide your code sample that results in the problem? Thanks.
Please note that get_all is a decorator method. It is not supposed to be used on its own like a regular method/function. As such, it is absent from the list of Trader class methods in the API documentation.

**Comment by Air2Air2Git** [comment]
Hello! Yes, I wasn't using get_all directly. I started digging into the code after encountering duplicates in the data that was pulled using the documented get_account_activities function. Here's the code I'm using (relevant parts):
```
class QT_class:
    def __init__(self,
        rt_file="my_token.txt"):
            self.rt_file = rt_file
            self.qs = kwess.Trader(rt_file=rt_file)

    def get_activities(self, acct_type, start, end=None):
        gen = self.qs.get_account_activities(start, end, accounttype=acct_type, verbose="vvv")
        result_list = []
        for item in gen:
            result_list = result_list + item["activities"]
        return result_list
```

Then, using the above class:
```
qt = qt_module.QT_class()
start=dt(2015, 10, 1)
end=dt(2016, 12, 31)
activities_list = qt.get_activities("margin", start=start, end=end)
```
The verbosity setting generates output such as this (sanitized) where you can see the endDate of previous range equals the startDate of next one:
```
{'startTime': '2015-10-01T00:00:00-04:00', 'endTime': '2015-10-30T00:00:00-04:00'}
{'activities': [.....]}
{'startTime': '2015-10-30T00:00:00-04:00', 'endTime': '2015-11-28T00:00:00-04:00'}
{'activities': [.....]}
...
{'startTime': '2016-08-15T00:00:00-04:00', 'endTime': '2016-09-13T00:00:00-04:00'}
{'activities': [.....]}
{'startTime': '2016-09-13T00:00:00-04:00', 'endTime': '2016-10-12T00:00:00-04:00'}
{'activities': [.....]}
```
Then convert the list of activities into dataframe and check for duplicates:
```
activities_df = pd.DataFrame(activities_list)
df_dup = activities_df[activities_df.duplicated(keep=False)]
```
And here's the duplicate records:
```
df_dup[["tradeDate", "action", "symbol", "description", "currency", "quantity", "price", "grossAmount", "commission", "netAmount"]]

                           tradeDate action  symbol                                        description currency  quantity  price  grossAmount  commission  netAmount
2   2015-11-27T00:00:00.000000-05:00    Buy  CGL.TO  ISHARES GOLD BULLION ETF       HEDGED COM UNIT...      CAD        50   9.32       -466.0       -0.17    -466.17
10  2015-11-27T00:00:00.000000-05:00    Buy  CGL.TO  ISHARES GOLD BULLION ETF       HEDGED COM UNIT...      CAD        50   9.32       -466.0       -0.17    -466.17
39  2016-09-13T00:00:00.000000-04:00    DIV  HNY.TO  HORIZONS NATURAL GAS YIELD     ETF            ...      CAD         0   0.00          0.0        0.00       3.06
40  2016-09-13T00:00:00.000000-04:00    DIV  HEP.TO  HORIZONS ENHANCED INCOME       GOLD PRODUCERS ...      CAD         0   0.00          0.0        0.00       5.62
42  2016-09-13T00:00:00.000000-04:00    DIV  HNY.TO  HORIZONS NATURAL GAS YIELD     ETF            ...      CAD         0   0.00          0.0        0.00       3.06
43  2016-09-13T00:00:00.000000-04:00    DIV  HEP.TO  HORIZONS ENHANCED INCOME       GOLD PRODUCERS ...      CAD         0   0.00          0.0        0.00       5.62
```
As a temporary fix I copied your get_all method and modified it to generate a list of start/end dates that I then feed into the get_account_activities without triggering the 30 day limit. I had to change the two lines:
```
startdatetime = idt
```
into:
```
startdatetime = idt + timedelta(days=1)
```
so that the dates don't overlap. Of course, please let me know if I'm just doing something wrong.
Thank you!

**Comment by kaiyoux** [comment]
You're right indeed. I've made the correction. Thank you very much.

**Comment by kaiyoux** [comment]
> Hello! Yes, I wasn't using get_all directly. I started digging into the code after encountering duplicates in the data that was pulled using the documented get_account_activities function. Here's the code I'm using (relevant parts):
> 
> ```
> class QT_class:
>     def __init__(self,
>         rt_file="my_token.txt"):
>             self.rt_file = rt_file
>             self.qs = kwess.Trader(rt_file=rt_file)
> 
>     def get_activities(self, acct_type, start, end=None):
>         gen = self.qs.get_account_activities(start, end, accounttype=acct_type, verbose="vvv")
>         result_list = []
>         for item in gen:
>             result_list = result_list + item["activities"]
>         return result_list
> ```
> 
> Then, using the above class:
> 
> ```
> qt = qt_module.QT_class()
> start=dt(2015, 10, 1)
> end=dt(2016, 12, 31)
> activities_list = qt.get_activities("margin", start=start, end=end)
> ```
> 
> The verbosity setting generates output such as this (sanitized) where you can see the endDate of previous range equals the startDate of next one:
> 
> ```
> {'startTime': '2015-10-01T00:00:00-04:00', 'endTime': '2015-10-30T00:00:00-04:00'}
> {'activities': [.....]}
> {'startTime': '2015-10-30T00:00:00-04:00', 'endTime': '2015-11-28T00:00:00-04:00'}
> {'activities': [.....]}
> ...
> {'startTime': '2016-08-15T00:00:00-04:00', 'endTime': '2016-09-13T00:00:00-04:00'}
> {'activities': [.....]}
> {'startTime': '2016-09-13T00:00:00-04:00', 'endTime': '2016-10-12T00:00:00-04:00'}
> {'activities': [.....]}
> ```
> 
> Then convert the list of activities into dataframe and check for duplicates:
> 
> ```
> activities_df = pd.DataFrame(activities_list)
> df_dup = activities_df[activities_df.duplicated(keep=False)]
> ```
> 
> And here's the duplicate records:
> 
> ```
> df_dup[["tradeDate", "action", "symbol", "description", "currency", "quantity", "price", "grossAmount", "commission", "netAmount"]]
> 
>                            tradeDate action  symbol                                        description currency  quantity  price  grossAmount  commission  netAmount
> 2   2015-11-27T00:00:00.000000-05:00    Buy  CGL.TO  ISHARES GOLD BULLION ETF       HEDGED COM UNIT...      CAD        50   9.32       -466.0       -0.17    -466.17
> 10  2015-11-27T00:00:00.000000-05:00    Buy  CGL.TO  ISHARES GOLD BULLION ETF       HEDGED COM UNIT...      CAD        50   9.32       -466.0       -0.17    -466.17
> 39  2016-09-13T00:00:00.000000-04:00    DIV  HNY.TO  HORIZONS NATURAL GAS YIELD     ETF            ...      CAD         0   0.00          0.0        0.00       3.06
> 40  2016-09-13T00:00:00.000000-04:00    DIV  HEP.TO  HORIZONS ENHANCED INCOME       GOLD PRODUCERS ...      CAD         0   0.00          0.0        0.00       5.62
> 42  2016-09-13T00:00:00.000000-04:00    DIV  HNY.TO  HORIZONS NATURAL GAS YIELD     ETF            ...      CAD         0   0.00          0.0        0.00       3.06
> 43  2016-09-13T00:00:00.000000-04:00    DIV  HEP.TO  HORIZONS ENHANCED INCOME       GOLD PRODUCERS ...      CAD         0   0.00          0.0        0.00       5.62
> ```
> 
> As a temporary fix I copied your get_all method and modified it to generate a list of start/end dates that I then feed into the get_account_activities without triggering the 30 day limit. I had to change the two lines:
> 
> ```
> startdatetime = idt
> ```
> 
> into:
> 
> ```
> startdatetime = idt + timedelta(days=1)
> ```
> 
> so that the dates don't overlap. Of course, please let me know if I'm just doing something wrong. Thank you!

You're right indeed. I've made the correction. Thank you very much.

**Comment by Air2Air2Git** [comment]
> You're right indeed. I've made the correction. Thank you very much.

It's working great now. And the whole wrapper is very useful! Thank you!
